restart_file: .na
start_datetime: 2010-07-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2010-12-31 00:00:00
forecast_horizon: 0.0
sim_name: ALEX_test
configure_flare: configure_flare.yml
configure_obs: observation_processing.yml
use_s3: no
